### ISSUE TITLE
PLugin doesnt work, Maps Dupe

### ISSUE THREAD

**Issue by cigagar** [KasperFranz/BetterChunkLoader#11]
So yea, suddenly the Chunkloaders dont work anymore. You can right click the iron block and it will give you the GUI, but you can click on the items, you can move the items around and put them in your inventory.

Also this error is given in Console: `[Sponge]: Could not pass ClickInventoryEvent$Primary$Impl to Plugin{id=betterchunkloader, name=BetterChunkLoader, version=1.0, authors=[KaiNoMood, Rob5Underscores, KasperFranz], source=/home/beyond/Minecraft/mods/*Plugin-BetterChunkLoader-3.0.jar}`

**Comment by KasperFranz** [comment]
Please share the full log since we had you currently us sharing doesn't help me narrow it down

**Comment by merjilin** [comment]
I have had the same issue but had no error posted. I could merely move the maps out of the gui and no chunkloader was created. I was using SF 2264 when this happened, and it seems a downgrade to 2259 has fixed it. If you look at bloodshot's changes to SF 2262, it states "Add missing NameCause to SpongeChunkGeneratorForge" That might be the reason why that particular event is nolonger triggering.

**Comment by KasperFranz** [comment]
I still need a full log - I will however try it out on my test server now

**Comment by merjilin** [comment]
Here's is the FML log:
https://gist.github.com/merjilin/fe239406c85739539fd3fb1c54491776

**Comment by KasperFranz** [comment]
I can't see the issue in that crash log sadly

**Comment by merjilin** [comment]
Yeah, :/ No error is printed for me. It just doesn't activate the chunk loader and allows me to drag the maps out of the gui.

**Comment by KasperFranz** [comment]
updating my setup now - will have a look

**Comment by KasperFranz** [comment]
Hmm you are right - gonna look into it now

**Comment by KasperFranz** [comment]
I just pushed some code to github - can you try this build out?
https://github.com/KasperFranz/BetterChunkLoader/releases/download/3.1.0/BetterChunkLoader-3.1.0.jar (made as a beta build for now)

**Comment by merjilin** [comment]
yep. Give me a second to re-update the server.

**Comment by KasperFranz** [comment]
it prints some debug when changing stuff, but that is fixed when i make the final 3.1 build

**Comment by merjilin** [comment]
it dropped the map upon the gui closing

**Comment by KasperFranz** [comment]
Which other mods are you running? more so i can get the same test setup

**Comment by KasperFranz** [comment]
I have now tried with both 2262 and 2264 without any problems

**Comment by merjilin** [comment]
I'm on FTB beyond version 1.2.1. Plugin wise I'm trying to figure out a way to send them you since GitHub doesn't allow me to upload jars here.

**Comment by KasperFranz** [comment]
What SpongeForge version?

**Comment by merjilin** [comment]
2264

**Comment by merjilin** [comment]
I'm wondering whether this link will work for the plugins: https://www.dropbox.com/sh/fmlncvarllpzwb9/AABUJcUTB1xc6hw3sjTtmzZYa?dl=0

**Comment by KasperFranz** [comment]
Try this 
https://github.com/KasperFranz/BetterChunkLoader/releases/download/3.1.0-pre2/BetterChunkLoader-3.1.0.jar

**Comment by merjilin** [comment]
Okay, the map is no longer being dropped. However, it seems that it is uses quite a bit of cpu power. Timings: https://timings.aikar.co/?id=b0ca599a9395456ea8ed28d7acffe00c

**Comment by KasperFranz** [comment]
I haven't seen that on my setup - can i get you to make another issue if this is still an issue?

**Comment by merjilin** [comment]
It seems to be fine now. Must've been the initial opening of the gui.
