### ISSUE TITLE
BCLForgeLib + Latest BCL installed, people are unable to create ChunkLoaders

### ISSUE THREAD

**Issue by micheldewit** [KasperFranz/BetterChunkLoader#15]
As per title: 
We have BCLForgeLib + the Latest BCL installed, and per principle it should work: However, When you select the Chunkloader you wish to install, it does nothing.. Absolutely nothing. 
Here are a few Screenshots: 
Sponge version and subinfo: 
http://i.imgur.com/xceX5Xn.jpg
Loaded Plugins: 
http://i.imgur.com/JZORMzx.jpg
All Mods installed: 
http://i.imgur.com/cbi8uwz.jpg
Screenshot of the block:
http://i.imgur.com/3j2Zud6.jpg
SelectionScreen: 
http://i.imgur.com/2H62tI6.jpg
The dragging of the selection screen and not actually being capable of selecting the selection screen.. 
http://i.imgur.com/qmj1D81.jpg

This is the issue what we are currently experiencing since we had to update Sponge because of the update of the modpack. 

Hereby a Pastebin of the ServerLog: 
https://pastebin.com/MpciZjUh

**Comment by micheldewit** [comment]
Found after searching your download archives an updated version of BCL.. That took care of the issues.

**Comment by KasperFranz** [comment]
Perfect - and my CI is down now because I changed hardware - gonna make a release of the version
