### ISSUE TITLE
Could not pass FMLServerStoppedEvent to Plugin

### ISSUE THREAD

**Issue by merjilin** [KasperFranz/BetterChunkLoader#16]
Hey! I've recently ran into this issue and I'm confused as to what might be causing it. Upon the server being restarted, this error is pasted to console: https://pastebin.com/ijudnSwE Thank you for your time - merj

**Comment by KasperFranz** [comment]
I will look into tthis tomorrow evening (in ~34 hours or so)

**Comment by KasperFranz** [comment]
It is fixed in [3.3.0](https://github.com/KasperFranz/BetterChunkLoader/releases/tag/3.3.0) :)
