### ISSUE TITLE
Chunks kept loaded even they shouldnt be

### ISSUE THREAD

**Issue by sentork** [KasperFranz/BetterChunkLoader#18]
Chunks are being loaded even tho the players aren't on, they stay loaded. 

http://prntscr.com/fedhgp

**Comment by KasperFranz** [comment]
That is the overall, not what is currently loaded - I will keep this issue open so I can change so it is only showing online information instead.

**Comment by KasperFranz** [comment]
This is fixed in the latest dev build https://github.com/KasperFranz/BetterChunkLoader/commit/c921a28b07f9562721053d597accfff6607bf21c
