### ISSUE TITLE
Map Chest

### ISSUE THREAD

**Issue by nosibor** [KasperFranz/BetterChunkLoader#19]
I've gotten the plugin and bclforge installed as well as my database setup, whenever I right click an iron block with a blaze rod I get the chest interface with maps. Whenever I click on the maps it removes them from the inventory rather than setting up the chunkloader. This happens with both an opped player and player with default permissions. I receive no error messages in game or in console.

**Comment by KasperFranz** [comment]
What versions are you using?
(SpongeForge, BCLForgeLib and BetterChunkLoader version)

**Comment by nosibor** [comment]
Sponge: spongeforge-1.10.2-2281-5.2.0-BETA-2464
BCLForgeLib: bclforgelib-1.1.20
BetterChunkLoader: BetterChunkLoader-3.0

**Comment by KasperFranz** [comment]
Update to the latest BetterChunkLoader either from the CI server or from the release page
