### ISSUE TITLE
Better error handling on load 

### ISSUE THREAD

**Issue by Whazaaaaa** [KasperFranz/BetterChunkLoader#20]
Hai I'm getting this but there no other information whatsoever on what is happening. Or what I did wrong in the config :(
28.09 20:48:40 [Server] Server thread/INFO [betterchunkloader]: Loading config...
28.09 20:48:40 [Server] Server thread/ERROR [betterchunkloader]: Load failed!

Perhaps some more info for a future version on whats going wrong?

## My Config
https://pastebin.com/iB2uvqTK

NOTE: I am using a ! in my password. If that is an issue

So to me it seems that  everything should be okay. I am able to login to the mysql user through my phpmyadmin panel as well so its not the wrong username/password. It just seems to fail somehow and I cant figure out why.

Any help would be much appreciated

**Comment by Whazaaaaa** [comment]
Aaaaaaaaaaaaand I put quotes around my password and it seems to work again :/
Sorry for the trouble.

**Comment by KasperFranz** [comment]
I just reopened so we can make a better error handling on this part
