### ISSUE TITLE
Suggestion: Alternate database save methods

### ISSUE THREAD

**Issue by JadenDevon** [KasperFranz/BetterChunkLoader#25]
Could you make it so that the chunkloader database is saved as either a .db file or a .yml so that mySQL is not required?

**Comment by KasperFranz** [comment]
I haven't seen any good use cases where you would like it to be a SQLite database.

I don't have any plans on adding support for a yml based system.

Can you share in which use case you would use SQLite database?

**Comment by JadenDevon** [comment]
Specifically in my case, when I first got the plugin, I had to ask my community founder to get access to a mySQL server. Then, the box that the database was on was shut down without my knowledge (which goes back to the issue that I had at that one point with an updated version of BCL). Then I had to wait a week while the community manager got in touch with our founder to get a new database set up. We lost the whole database and it could have been avoided if the file was stored locally in the MC server files.

**Comment by KasperFranz** [comment]
That is now in develop and will be part of 3.9
