### ISSUE TITLE
NPE on /bcl purge

### ISSUE THREAD

**Issue by Warhawker** [KasperFranz/BetterChunkLoader#27]
Mc version 1.12
Spongeforge 7.1.6
FTB Revelations upgrade 2.7.0 -> 3.0.1
Better Chunkloaders 3.7.0 S 7.1.0
LuckPerms

We created a new map, and while the server was running performed /bcl purge to clean the database.
The command did not run, and returned a NullPointerException.
`7.05 18:19:16 [Server] Server thread/ERROR [Sponge]: Error occurred while executing command 'bcl purge' for source EntityPlayerMP['Warhawker'/602, l='Vile Nation', x=-219.75, y=76.24, z=-15.64]: null
27.05 18:19:16 [Server] INFO java.lang.NullPointerException: null
27.05 18:19:16 [Server] INFO at net.kaikk.mc.bcl.BetterChunkLoader.unloadChunks(BetterChunkLoader.java:289) ~[BetterChunkLoader.class:?]
27.05 18:19:16 [Server] INFO at net.kaikk.mc.bcl.datastore.AHashMapDataStore.removeChunkLoader(AHashMapDataStore.java:105) ~[AHashMapDataStore.class:?]
27.05 18:19:16 [Server] INFO at net.kaikk.mc.bcl.datastore.MySqlDataStore.removeChunkLoader(MySqlDataStore.java:162) ~[MySqlDataStore.class:?]
27.05 18:19:16 [Server] INFO at net.kaikk.mc.bcl.commands.CmdPurge.execute(CmdPurge.java:37) ~[CmdPurge.class:?]
27.05 18:19:16 [Server] INFO at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.5]
27.05 18:19:16 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.5]
27.05 18:19:16 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.5]
27.05 18:19:16 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.5]
27.05 18:19:16 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
27.05 18:19:16 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
27.05 18:19:16 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
27.05 18:19:16 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
27.05 18:19:16 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
27.05 18:19:16 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.5]
27.05 18:19:16 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zli000(SourceFile:539) [hv$1.class:?]
27.05 18:19:16 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
27.05 18:19:16 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
27.05 18:19:16 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
27.05 18:19:16 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
27.05 18:19:16 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:297) [SpongeImplHooks.class:1.12.2-2768-7.1.5]
27.05 18:19:16 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zjm000(MinecraftServer.java:3963) [MinecraftServer.class:?]
27.05 18:19:16 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
27.05 18:19:16 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
27.05 18:19:16 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
27.05 18:19:16 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
27.05 18:19:16 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]`

After manually clearing the MySQL tables, the chunks were reset and plugin functionality is normal as expected.

**Comment by KasperFranz** [comment]
This is fixed in development and will be in the next release :)
