### ISSUE TITLE
[Feature Request] Make MYSQL optional

### ISSUE THREAD

**Issue by s-kk** [KasperFranz/BetterChunkLoader#28]
Dear developer!
I appreciate the plugin very much, but one thing that's stopping me from using it is that it requires a MySQL database, which is almost unaffordable for my server.
Is it possible to replace it with a lighter SQLite?
Thanks!

**Comment by KasperFranz** [comment]
Adding another data storage than MySQL has already been suggested in #25.

MySQL should not be a problem - most server hosts wouldn't mind helping you with a MySQL server on the same box that your Dedicated / Virtual server is running on.

I am closing this ticket as there is already one to cover this feature request
