### ISSUE TITLE
Admin Loader not working

### ISSUE THREAD

**Issue by blairwilson** [KasperFranz/BetterChunkLoader#29]
Admin loaders don't seem to work anymore, checking /lp verbose when placing a CL it doesn't check my perms for betterchunkloader.adminloader and the loader follows the normal rules of deactivating after X hours defined in config.

**Comment by KasperFranz** [comment]
Are you using the correct commands?

**Comment by KasperFranz** [comment]
When you check the block is it listed as an admin block?

**Comment by KasperFranz** [comment]
I would also need more info about your system (what versions of the plugin, sponge version)

**Comment by KasperFranz** [comment]
No comments received on this - please reopen when you got more info
