### ISSUE TITLE
Make config reloadable if sql connection fails

### ISSUE THREAD

**Issue by clienthax** [KasperFranz/BetterChunkLoader#34]
While configuring the plugin, if the sql connection fails, no commands are registered.
And there is no way to reload the config via the sponge plugins reload command
 https://docs.spongepowered.org/stable/en/plugin/event/listeners.html#gamereloadevent

**Comment by KasperFranz** [comment]
That is now implemented in the latest RC - still not 100% tested but it is a starting point :)
