### ISSUE TITLE
Crashing with Bstats because of other plugins with wrong version 

### ISSUE THREAD

**Issue by cow0075** [KasperFranz/BetterChunkLoader#44]
**What is the bug?**
BCL crashes spongeforge server with this crashreport:
[kRU5ECzR.txt](https://github.com/KasperFranz/BetterChunkLoader/files/5371080/kRU5ECzR.txt)

Works fine with BCL version 3.7.0.

- **Sponge Version:** 1.12.2-7.3.1
- **BetterChunkLoader Version:** 3.8.0 & 3.8.0-RC3
- **BCLForgeLib Version:** 1.12.2-1.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Download and run mcethernal minecraft server.
2. Add spongeforge and mods necessary to run BCL and the BCL mod itself.
3. See the crash report.

**Expected behaviour**
Server not to crash on start and plugin to generate config so i can setup databases.

**Comment by KasperFranz** [comment]
Can you please put the log/crash report in a gist?

**Comment by KasperFranz** [comment]
Where did you download it from?

**Comment by KasperFranz** [comment]
It is fixed in latest now (not released yet)
