### ISSUE TITLE
Command to remove a chunkloader

### ISSUE THREAD

**Issue by Alydus** [KasperFranz/BetterChunkLoader#54]
**Is your feature request related to a problem? Please describe.**
Sometimes the block configured to be a blockloader can be ugly, and not fit the theme of a base or location a player has built, therefore they may want to hide it in a floor, wall, etc, leaving them to forget where their chunkloader is located if they need to remove it in future. Although /bcl list will list the coordinates of the chunkloaders, this is still user unfriendly to go and locate them, just to remove them.

**Describe the solution you'd like**
A command to remove a chunkloader (list them 1, 2, 3 in /bcl list?), it returns the block used to create the chunkloader to the users inventory, if full, it'll drop it to the ground below the player (could also fail the command with a warning their inventory is full), the chunkloader is then removed from the world where it is located.

Command could be named /bcl remove (chunkloader id)

**Describe alternatives you've considered**
I also thought of perhaps a command to help find the chunkloaders based on chunks, a similar feature is in popular minecraft factions plugins, where they show a map in chat of all of the chunks nearby to the player, it could highlight the chunks where chunkloaders exist, but this still isn't narrowing it down to a single block.

**Additional context**
N/A

**Comment by KasperFranz** [comment]
You can actually already do that by using the /bcl list and give the user the permission `betterchunkloader.list.delete.own` then they can delete their own chunkloaders :)
