### ISSUE TITLE
Removing a chunkloader block with a non 1x1 digging tool does not register it has been removed

### ISSUE THREAD

**Issue by Alydus** [KasperFranz/BetterChunkLoader#55]
**What is the bug?**
When mining to remove a chunkloader block using a modded tool that digs in a 3x3, 3x3x3, 5x5, 9x9 etc, if the chunkloader isn't the first block aimed at when mining, it will not register the chunkloader has been removed.

I have only tested this with Fluxbore tools from Redstone Arsenal, however I expect the exact same thing to happen with other similar tools from different mods.

- **Sponge Version: spongeforge-1.12.2-2838-7.3.0.jar**
- **BetterChunkLoader Version: BetterChunkLoader-3.8.2-S7.1.0-ore.jar**
- **BCLForgeLib Version: bclforgelib-1.12.2-1.1.jar**

**To Reproduce**
Steps to reproduce the behaviour:
1. Install FTB Revelations 3.4.0, or any other modpack in 1.12 with Fluxbores from Redstone Arsenal
2. Go into a world, give yourself a resonant fluxbore, fully charged
3. Press V, or cycle item mode keybind, to switch to a mode that isn't 1x1/default, e.g. 3x3
4. Place a chunkloader, register it as 1x1 or any size, then dig a block adjacent to the chunkloader, notice the chunkloader isn't unregistered, and the user isn't notified in chat

**Expected behaviour**
Chunkloader is unregistered and no longer visible from /bcl list, and the balance is restored when destroyed in the world

**Comment by KasperFranz** [comment]
@Alydus 
That is interesting - we are here relaying on the events fired from sponge - but I will test this out and hopefully find a solution for it :)

**Comment by KasperFranz** [comment]
This is now fixed in the development version :)
