### ISSUE TITLE
No class found error

### ISSUE THREAD

**Issue by blairwilson** [KasperFranz/BetterChunkLoader#57]
Hey, I have been using BCL for a good while now and specifically on my MC Eternal server it crashes on startup.

https://gist.github.com/blairwilson/79b7f92387e4b8d4c467e66901556596

**Comment by KasperFranz** [comment]
Is this still an issue? 

I would suggest you download the forge mod and the sponge plugin from GitHub again

**Comment by KasperFranz** [comment]
@blairwilson  any luck?

**Comment by blairwilson** [comment]
> @blairwilson  any luck?

Hey! I ended up just making my own chunkloading plugin for use on Eternal so didn't get a chance to double check but if you can i'd test the plug-in on MC Eternal server V1.4.4 with Sponge 7.3.0 as that's what i was using when getting the issue :(

**Comment by KasperFranz** [comment]
It seems like this was caused by using an old version of the forge lib (v1)
